#!/bin/bash

# Install required packages
sudo apt-get update && apt upgrade
sudo apt-get install -y vim tmux git net-tools 

# Configure Vim
echo 'syntax enable' >> ~/.vimrc
echo 'colorscheme ron' >> ~/.vimrc

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Create Tmux configuration file
echo 'run-shell ~/.tmux/plugins/tpm/tpm' > ~/.tmux.conf
echo 'source ~/.tmux/plugins/tpm/tpm.conf' >> ~/.tmux.conf
echo 'set -g @plugin "tpm"' >> ~/.tmux.conf
echo 'set -g @plugin "tmux-plugins/tmux-sensible"' >> ~/.tmux.conf
echo 'set -g @plugin "tmux-plugins/tmux-yank"' >> ~/.tmux.conf
echo 'set -g @plugin "tmux-plugins/tmux-resurrect"' >> ~/.tmux.conf

# Install Tmux plugins
~/.tmux/plugins/tpm/bin/install_plugins

# Print completion message
echo "Setup completed successfully!"
