#!/bin/bash

# Author : cosmo
# Script follows here:


# Install required packages/tools
sudo apt update -y
sudo apt install vim tmux git net-tools xsel -y

# Configure Vim
echo 'syntax enable' >> /home/$1/.vimrc
echo 'colorscheme ron' >> /home/$1/.vimrc

cd /home/$1
# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm /home/$1/.tmux/plugins/tpm

tmux

tmux show-options -g | sed 's/^/set -g /' > /home/$1/.tmux.conf

# Adding few lines of commands for tmux-plugins

echo "

# Installed on purpose
set -g mouse on
set -g @shell_mode 'vi'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

run '/home/$1/.tmux/plugins/tpm/tpm'
run-shell /home/$1/.tmux/plugins/tmux-resurrect/resurrect.tmux
irun-shell /home$1/.tmux/plugins/tmux-yank/yank.tmux" >>.tmux.conf


source /home/$1/.tmux.conf
