#!/bin/bash

# Author : cosmo
#USAGE: 
#- pick a file as per the compatible os and install as below
# switch user to 'root' user
# ./download_yum (installs all packages and configures tmux)
# open tmux using 'tmux' and then refresh and reload tmux using
#'prefix(ctrl+b) and I'

# Script follows here:

# Install required packages/tools
apt update -y
apt install vim tmux -y

# Configure Vim
echo 'syntax enable' >> /data/data/com.termux/files/usr/etc/vimrc
echo 'colorscheme ron' >> /data/data/com.termux/files/usr/etc/vimrc

source /data/data/com.termux/files/usr/etc/vimrc

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm /data/data/com.termux/files/usr/etc/tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tmux-resurrect /data/data/com.termux/files/usr/etc/tmux/plugins/tmux-resurrect
git clone https://github.com/tmux-plugins/tmux-yank /data/data/com.termux/files/usr/etc/tmux/plugins/tmux-yank

tmux new -d -s test
tmux show-options -g | sed 's/^/set -g /' > /data/data/com.termux/files/usr/etc/tmux.conf

# Adding few lines of commands for tmux-plugins

echo "

# Installed on purpose
set -g mouse on
set -g @shell_mode 'vi'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)

run '/data/data/com.termux/files/usr/etc/tmux/plugins/tpm/tpm'
run-shell /data/data/com.termux/files/usr/etc/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell /data/data/com.termux/files/usr/etc/tmux/plugins/tmux-yank/yank.tmux" >>.tmux.conf

tmux source-file /data/data/com.termux/files/usr/etc/tmux.conf
