#!/bin/bash

# Author : cosmo
# Script follows here:

# Install required packages/tools
sudo apt update -y
sudo apt install vim tmux git net-tools xsel -y

# Configure Vim
echo 'syntax enable' >> /etc/vimrc
echo 'colorscheme ron' >> /etc/vimrc

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm /etc/tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tmux-resurrect /etc/tmux/plugins/tmux-resurrect
git clone https://github.com/tmux-plugins/tmux-yank /etc/tmux/plugins/tmux-yank

# Opening tmux in detatched mode
tmux new -d -s test

tmux show-options -g | sed 's/^/set -g /' 1 >/etc/tmux.conf

# Adding few lines of commands for tmux-plugins

echo "

# Installed on purpose
set -g mouse on
set -g @shell_mode 'vi'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '/etc/tmux/plugins/tpm/tpm'
run-shell /etc/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell /etc/tmux/plugins/tmux-yank/yank.tmux" >>/etc/tmux.conf

source /etc/tmux.conf
