#!/bin/bash

# Author : cosmo
# Script follows here:

# Install required packages/tools
sudo apt update -y
sudo apt install vim tmux git net-tools xsel -y

# Configure Vim
cat > /etc/vim/vimrc << eof
syntax enable
colorscheme ron
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType groovy setlocal ts=2 sts=2 sw=2 expandtab
eof

source $1/.vimrc

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm $1/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tmux-resurrect $1/.tmux/plugins/tmux-resurrect
git clone https://github.com/tmux-plugins/tmux-yank $1/.tmux/plugins/tmux-yank
git clone https://github.com/tmux-plugins/tmux-continuum $1/.tmux/plugins/tmux-continuum

# Opening tmux in detatched mode
tmux new -d -s test

tmux show-options -g | sed 's/^/set -g /' >$1/.tmux.conf

# Adding few lines of commands for tmux-plugins

echo "
# Installed on purpose
set -g @continuum-restore 'on'
set -g mouse on
set -g @shell_mode 'vi'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$1/.tmux/plugins/tpm/tpm'
run-shell $1/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell $1/.tmux/plugins/tmux-yank/yank.tmux
run-shell $1/.tmux/plugins/tmux-continuum/continuum.tmux">>$1/.tmux.conf 

tmux source-file $1/.tmux.conf
