#!/bin/bash

# Author : cosmo
# Script follows here:

# Install required packages/tools
sudo apt update -y
sudo apt install vim tmux git net-tools xsel -y

# Configure Vim
cat > /etc/vim/vimrc << eof
syntax enable
colorscheme ron
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType groovy setlocal ts=2 sts=2 sw=2 expandtab
eof

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Opening tmux in detatched mode
tmux new -s test -d

tmux show-options -g | sed 's/^/set -g /' >~/.tmux.conf

# Adding few lines of commands for tmux-plugins
echo "
# Installed on purpose
set -g mouse on
set -g @shell_mode 'vi'
set -g @yank_selection_mouse 'clipboard' # or 'primary' or 'secondary'
set -g @continuum-restore 'on'
set -g status-right '#{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'">>~/.tmux.conf 

tmux source-file ~/.tmux.conf
