#!/bin/bash
  
# Install required packages
sudo apt update -y
sudo apt install vim tmux git net-tools xsel -y

# Configure Vim
echo 'syntax enable' >> /home/$1/.vimrc
echo 'colorscheme ron' >> /home/$1/.vimrc
echo 'set number' >> /home/$1/.vimrc

# Install Tmux Plugin Manager (TPM)
git clone https://github.com/tmux-plugins/tpm /home/$1/.tmux/plugins/tpm


echo 'set -g @plugin "tmux-plugins/tmux-sensible"' >>$file
echo 'set -g @plugin "tmux-plugins/tmux-yank"' >> $file
echo 'set -g @plugin "tmux-plugins/tmux-resurrect"' >>$file

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
echo "run '~/.tmux/plugins/tpm/tpm'" >> $file

source $file

#^b
#"I
